[project]
name = "main"
version = "0.0.0"
dependencies = ["logging", "langchain", "langchain_openai", "google-search-results", "langchain_community", "redis", "langsmith", "requests"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

